kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-openshift-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift-blue
  template:
    metadata:
      labels:
        app: hello-openshift-blue
    spec:
      containers:
      - name: hello-openshift-blue
        image: 172.30.1.1:5000/training15/hello-openshift:2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 9080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /hello-openshift/resources/hello
            port: 9080
            scheme: HTTP
          initialDelaySeconds: 30
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
